### ISSUE TITLE
It doesn't show any files under a directory.

### ISSUE THREAD

**Issue by qazmichaelgw** [Backblaze-B2-Samples/b2fs4chia#5]
When mounted, it doesn't show any file under that bucket but only the directory structure.

**Comment by ppolewicz** [comment]
https://github.com/Backblaze-B2-Samples/b2fs4chia/blob/58825b16ef1d680657563b21713fc79aae223f69/b2fuse/b2fuse_main.py#L139 @mpnowacki-reef I think this should have a `recursive=True`, right?

**Comment by ppolewicz** [comment]
fixed by #6, we think
